<?php include_once(VIEW_PATH . '/layout/header.phtml') ?>

    <div class="container">
        <div class="err404">
            <p>抱歉，<br><br><br><br></p>
            <p>美女走了，页面无法打开！</p>
            <p class="err404-baseline"><a href="/">返回首页</a>&nbsp;或&nbsp;<a href="/contact/">联系我们</a></p>
        </div>
    </div>

<?php include_once(VIEW_PATH . '/common/list.phtml') ?>

<?php include_once(VIEW_PATH . '/layout/footer.phtml') ?>