<!DOCTYPE html>
<html>
<head>
    <?php include_once(VIEW_PATH . '/common/header.phtml'); ?>
</head>
<body>
<header class="header">
    <div class="center-ctnr">
        <div class="container">
            <a href="/" class="header-logo"></a>
            <div class="header-menu-ctnr">
                <a class="header-menu-btn" id="mobileMenusBtn" href="javascript:;">menu</a>
            </div>
        </div>
    </div>
</header>
<div class="center-ctnr main-ctnr">
    <div class="container clearfix">

    <div class="container">
        <div class="err404">
            <p>抱歉，<br><br><br><br></p>
            <p>美女走了，页面无法打开！</p>
            <p class="err404-baseline"><a href="/">返回首页</a>&nbsp;或&nbsp;<a href="/contact/">联系我们</a></p>
        </div>
    </div>

    <div style="display: none">
        <pre>
        <?php echo $code;?><br />
        <?php var_dump($msg);?>
        </pre>
    </div>

<?php include_once(VIEW_PATH . '/layout/footer.phtml') ?>