<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8">
    <title><?php echo $title;?></title>
    <link rel="stylesheet" href="/resources/style/lib/all.css"/>
    <link rel="stylesheet" href="/resources/style/app/all.css"/>
</head>
<body>
<div class="wrap">
    <div class="box">
        <div class="main">
            <div class="reglater">
                <a href="/" class="logo">不要集</a>
                <div class="choose-tags">
                    <div class="search-tags">
                        <div class="search-bar">
                            <input type="text" id="searchContent" class="text" placeholder="搜索感兴趣的标签..."/>
                            <input type="image" id="searchBtn" src="/resources/images/look.png">
                        </div>
                        <div class="tagslist" id="tagsList">
                        </div>
                    </div>
                    <div class="had-gz-tags">
                        <dl>
                            <dt><span class="num">已关注：10/10</span><strong>已关注的标签</strong></dt>
                            <dd id="listenedTags">
                            </dd>
                        </dl>
                    </div>
                    <a href="/" class="complete-reg">完成注册</a>
                </div>
            </div>
            <footer class="footer">
                <div class="links">
                    <a href="#">提问与建议</a>
                    <span>|</span>
                    <a href="#">合作联系</a>
                    <span>|</span>
                    <a href="#">关于我们</a>
                </div>
                <div class="copyright">2013 buyaoji.com  京ICP备 13010651号</div>
            </footer>
        </div>
    </div>
</div>
<script type="text/javascript" src="/resources/js/lib/seajs/sea.js" ></script>
<script type="text/javascript" src="/resources/js/lib/seajs/config.js"></script>
<script type="text/javascript">
    seajs.use('app/reg/listentag');
</script>
</body>
</html>