<form action="" class="makebox" id="albumForm">
    <table class="simple-form">
        <tr>
            <th>专辑名称：</th>
            <td>
                <input type="text" class="inputLarge" name="album_name" id="albumName">
            </td>
        </tr>
        <tr>
            <th>
                &nbsp;
            </th>
            <td>
                <ul class="editlist" id="albumContainer">
                </ul>
                <input type="button" value="+批量添加图片" id="pickfiles" class="addpic" />
            </td>
        </tr>
        <?php require_once('tag.phtml'); ?>
        <tr>
            <th></th>
            <td>
                <label><input type="radio" value="1" name="is_open" id="open" checked/>公开</label>
                <label><input type="radio" value="0" name="is_open" id="close"/>私密</label>
            </td>
        </tr>
        <tr>
            <th></th>
            <td>
                <a class="btn btn-small btn-important" href="javascript:;" id="submit">保存</a>
                &nbsp;
                <a class="btn btn-small btn-normal" href="javascript:;">取消</a>
            </td>
        </tr>
    </table>
</form>
<?php  include_once('editimage.phtml'); ?>
