<?php include_once(VIEW_PATH . '/layout/header.phtml') ?>

    <div class="page_title">
        <a href="main.html">&lt;&lt;返回首页</a>
    </div>
    <div class="page-title"><img src="images/icos/ico01.gif">做图集</div>
    <div class="clear"></div>
    <div class="makebox">
        <div class="pic-title">专辑名称：<input type="text"></div>
        <ul class="editlist" id="sortable">
            <li>
                <div class="libox">
                    <span class="up"></span>
                    <span class="down"></span>
                    <img src="images/01.jpg">
                    <textarea>可以在这里写下图片描述...</textarea>
                    <span class="deledtpic"></span>
                    <span class="bi"></span>
                </div>
            </li>
            <li>
                <div class="libox">
                    <span class="up"></span>
                    <span class="down"></span>
                    <img src="images/01.jpg">
                    <textarea>可以在这里写下图片描述...</textarea>
                    <span class="deledtpic"></span>
                    <span class="bi"></span>
                </div>
            </li>
        </ul>
        <input type="button" value="+批量添加图片" class="addpic" />
        <div class="tagsbox">
            <span class="name">添加标签：</span>
            <div class="tags">
                <span>标签1</span>
                <span>标签2</span>
                <span>标签3</span>
                <span>标签4</span>
                <span>标签5</span>
                <span>标签6</span>
            </div>
        </div>
        <div class="gz_tags">
            <dl>
                <dt>你关注的标签</dt>
                <dd>
                    <span>标签1</span>
                    <span>标签2</span>
                    <span>标签3</span>
                    <span>标签4</span>
                    <span>标签5</span>
                    <span>标签6</span>
                </dd>
            </dl>
        </div>
        <input type="button" value="订阅设置" class="ressset" /><br>
        <input type="button" value="保存"  class="save" />
        <input type="button" value="取消"  class="cancle" />
        <div class="editbox">
            <a href="javascript:;" class="close"></a>
            <h3>编辑图片</h3>
            <ul>
                <li>
                    <span class="name">图片布局</span>
                    <div class="pic-at-left choose pos-choose"><img src="images/ico_tu01.jpg"></div>
                    <div class="pic-at-middle pos-choose"><img src="images/ico_tu01.jpg"></div>
                    <div class="pic-at-right pos-choose"><img src="images/ico_tu01.jpg"></div>
                </li>
                <li>
                    <span class="name">描述位置</span>
                    <div class="ms-at-left choose pos-choose"><img src="images/ico_tu04.jpg"></div>
                    <div class="ms-at-middle pos-choose"><img src="images/ico_tu05.jpg"></div>
                    <div class="ms-at-right pos-choose"><img src="images/ico_tu06.jpg"></div>
                </li>
                <li>
                    <span class="name">设为封面</span>
                    <input type="checkbox">
                </li>
                <li class="cutbox">
                    <div class="cut">
                        <span class="mask"></span>
                        <img src="images/01.jpg">
                    </div>
                </li>
                <li class="btn" ><input type="button" value="保存"></li>
            </ul>
        </div>
    </div>

<?php include_once(VIEW_PATH . '/layout/footer.phtml') ?>