<?php include_once(VIEW_PATH . '/layout/header.phtml') ?>

<div class="page_title">
    <a href="main.html">&lt;&lt;返回首页</a>
</div>
<div class="page-title"><img src="images/icos/ico01.gif">做图集</div>
<div class="clear"></div>
<div class="makebox">
    <div class="pic-title">专辑名称：<input type="text"></div>
    <ul class="editlist" id="albumContainer">
    </ul>
    <!--<div id="container" style="position: relative;">
        <div id="filelist"><div>Current runtime: html5</div><div id="p17us9s9fj1p30ousebg111l14513">1329273979NKU5E2.jpg (514 KB) <b></b></div></div>
        <br>
        <div id="p17us8c9jb13qa8q0vn9ra752e0_html5_container" class="plupload html5" style="position: absolute; background-color: transparent; width: 86px; height: 16px; overflow: hidden; z-index: -1; opacity: 0; top: 48px; left: 0px; background-position: initial initial; background-repeat: initial initial;"><input id="p17us8c9jb13qa8q0vn9ra752e0_html5" style="font-size: 999px; position: absolute; width: 100%; height: 100%;" type="file" accept="image/jpeg,image/gif,image/png,application/zip" multiple="multiple"></div></div>-->
    <input type="button" value="+批量添加图片" id="pickfiles" class="addpic" />
    <div class="tagsbox">
        <span class="name">添加标签：</span>
        <div class="tags">
            <span>标签1</span>
            <span>标签2</span>
            <span>标签3</span>
            <span>标签4</span>
            <span>标签5</span>
            <span>标签6</span>
        </div>
    </div>
    <div class="gz_tags">
        <dl>
            <dt>你关注的标签</dt>
            <dd>
                <span>标签1</span>
                <span>标签2</span>
                <span>标签3</span>
                <span>标签4</span>
                <span>标签5</span>
                <span>标签6</span>
            </dd>
        </dl>
    </div>
    <input type="button" value="订阅设置" class="ressset" /><br>
    <input type="button" value="保存"  class="save" />
    <input type="button" value="取消"  class="cancle" />
    <div class="editbox">
        <a href="javascript:;" class="close"></a>
        <h3>编辑图片</h3>
        <ul>
            <li>
                <span class="name">图片布局</span>
                <div class="pic-at-left choose pos-choose"><img src="images/ico_tu01.jpg"></div>
                <div class="pic-at-middle pos-choose"><img src="images/ico_tu01.jpg"></div>
                <div class="pic-at-right pos-choose"><img src="images/ico_tu01.jpg"></div>
            </li>
            <li>
                <span class="name">描述位置</span>
                <div class="ms-at-left choose pos-choose"><img src="images/ico_tu04.jpg"></div>
                <div class="ms-at-middle pos-choose"><img src="images/ico_tu05.jpg"></div>
                <div class="ms-at-right pos-choose"><img src="images/ico_tu06.jpg"></div>
            </li>
            <li>
                <span class="name">设为封面</span>
                <input type="checkbox">
            </li>
            <li class="cutbox">
                <div class="cut">
                    <span class="mask"></span>
                    <img src="images/01.jpg">
                </div>
            </li>
            <li class="btn" ><input type="button" value="保存"></li>
        </ul>
    </div>
</div>
<script type="text/javascript">
    seajs.use('app/make/album');
</script>

<?php include_once(VIEW_PATH . '/layout/footer.phtml') ?>