<div id="editImage" class="win-content editbox">
    <ul>
        <li class="js-pic-pos">
            <span class="name">图片布局</span>
            <div data-align="0" class="js-choose pic-at-left choose pos-choose"><img src="/resources/images/makealbum_align_center.jpg"></div>
            <div data-align="2" class="js-choose pic-at-middle pos-choose"><img src="/resources/images/makealbum_align_left.jpg"></div>
            <div data-align="1" class="js-choose pic-at-right pos-choose"><img src="/resources/images/makealbum_align_right.jpg"></div>
        </li>
        <li class="js-txt-pos">
            <span class="name">描述位置</span>
            <div data-align="0" class="js-choose ms-at-left choose pos-choose"><img src="/resources/images/makealbum_textalign_center.jpg"></div>
            <div data-align="1" class="js-choose ms-at-middle pos-choose"><img src="/resources/images/makealbum_textalign_left.jpg"></div>
            <div data-align="2" class="js-choose ms-at-right pos-choose"><img src="/resources/images/makealbum_textalign_right.jpg"></div>
        </li>
        <li>
            <span class="name">设为封面</span>
            <input type="checkbox" name="is_cover"/>
        </li>
        <li class="cutbox">
            <div class="cut">
                <span class="mask"></span>
                <img class="js-editimage-thumb" src="/resources/images/devtmp_makealbum01.jpg">
            </div>
        </li>
        <li class="btn"><input type="button" class="js-save" value="保存"></li>
    </ul>
</div>