<?php include_once(VIEW_PATH . '/layout/header.phtml') ?>

    <div class="page_title">
        <span class=""><img src="/resources/icons/album.gif">编辑图集</span>
        <a href="main.html">&lt;&lt;返回首页</a>
    </div>

<?php include_once('albumform.phtml') ?>

    <script type="text/javascript">
        seajs.use('app/make/album', function(album) {
            $(function() {
                album.init($CONFIG.album_id);
            });
        });
    </script>

<?php include_once(VIEW_PATH . '/layout/footer.phtml') ?>