<div class="tagsbox">
    <span class="name">添加标签：</span>
    <div class="tags">
        <ul id="tagCtnr" style="float: left;"></ul>
        <input type="text" id="createTag" placeholder="添加标签"/>
        <span class="tags-msg"></span>
    </div>

</div>
<div class="gz_tags">
    <dl id="suggestTags">
        <dt>你关注的标签</dt>
    </dl>
    <p></p>
</div>
<script type="text/javascript">
    seajs.use('app/make/tag');
</script>