<?php include_once(VIEW_PATH .'/layout/header.phtml')?>

<div class="main">
<div class="bor_light1">
      <div class="bor_lightt1"></div>
      <div class="periphery">
      <dl class="perip_dl">
      <dt>家饰</dt>
      <dd><a href="#">摆件</a><a href="#">餐具</a><a href="#">杯子</a><a href="#">灯具</a><a href="#">摆件</a><a href="#">餐具</a><a href="#">杯子</a><a href="#">灯具</a><a href="#">摆件</a><a href="#">餐具</a><a href="#">杯子</a><a href="#">灯具</a></dd>
      </dl>
      <dl class="perip_dl1">
      <dt>家纺</dt>
      <dd><a href="#">摆件</a><a href="#">餐具</a><a href="#">杯子</a><a href="#">灯具</a><a href="#">摆件</a><a href="#">餐具</a><a href="#">杯子</a><a href="#">灯具</a><a href="#">摆件</a><a href="#">餐具</a><a href="#">杯子</a><a href="#">灯具</a></dd>
      </dl>
      <dl class="perip_dl2">
      <dt>家具</dt>
      <dd><a href="#">摆件</a><a href="#">餐具</a><a href="#">杯子</a><a href="#">灯具</a><a href="#">摆件</a><a href="#">餐具</a><a href="#">杯子</a><a href="#">灯具</a><a href="#">摆件</a><a href="#">餐具</a><a href="#">杯子</a><a href="#">灯具</a></dd>
      </dl>
      <dl class="perip_dl3">
      <dt>数码</dt>
      <dd><a href="#">摆件</a><a href="#">餐具</a><a href="#">杯子</a><a href="#">灯具</a><a href="#">摆件</a><a href="#">餐具</a><a href="#">杯子</a><a href="#">灯具</a><a href="#">摆件</a><a href="#">餐具</a><a href="#">杯子</a><a href="#">灯具</a></dd>
      </dl>
      <dl class="perip_dl4">
      <dt>家电</dt>
      <dd><a href="#">摆件</a><a href="#">餐具</a><a href="#">杯子</a><a href="#">灯具</a><a href="#">摆件</a><a href="#">餐具</a><a href="#">杯子</a><a href="#">灯具</a><a href="#">摆件</a><a href="#">餐具</a><a href="#">杯子</a><a href="#">灯具</a></dd>
      </dl>
      </div>
      <div class="bor_lightf1"></div>
    </div>
</div>
<div class="mwidth box">

<div class="top_tit"><div class="paixu">排序<span class="icon_ap">喜欢</span><span class="icon_up">价格</span></div>
<a href="javascript:;" class="tit_off">24小时最热</a><a href="javascript:;" class="tit_on">7天最热</a><a href="javascript:;" class="tit_on">TOP250</a>
</div>
  <div class="box_left top_list">
      <?php include_once(VIEW_PATH.'/index/list.phtml')?>
  </div>  
</div>

<?php include_once(VIEW_PATH.'/layout/footer.phtml')?>