<?php include_once(VIEW_PATH .'/layout/header.phtml')?>
    <div class="container">
    
    <div class="page-header">
    <h1>DoYaf <small>简单是一种美</small></h1>
	</div>
	<p>简介</p>
	<div class="tooltip-demo well">
	<p class="muted" style="margin-bottom: 0;">
	如果你是一名程序员，懂或不懂PHP，请继续；<br>
	即使你不懂程序，你只是想来体验一下什么是美好，请继续。<br>
	<br>
	简单是一种美好。<br>
	如果不能忍受上边的这一句，我想，您可以尝试用ZF框架开发一个CMS或去尝试听一听十＠大领悟一下精神，都是不错的选择。<br>
	<br>
	没错，任何一种编程语言都只是一种工具，它为了进步而存在，并且给我们的工作与生活带来了便捷。<br>
	PHP是其中一个。<br>
	<br>
	现在还有项目在使用PHP面向过程开发吗？如果有，千万不要在注释中写@author，当后人维护你的代码时，会问候这位@author的长辈。<br>
	当然，我们使用OOP；当然，我们使用开发框架。<br>
	我认为一个优秀的框架，应具备的四个特征是：<br>
		1、稳定、高性能<br>
		2、安全、可扩展<br>
		3、规范、有约束<br>
		4、简单、易学习<br>
	<br>
	我所追逐的是不仅是一种工具，而是“性能、安全、规范、简单”。<br>
	籍于此，
	我所推崇的“应用级”框架是“CI（CodeIgniter）”；
	另一个相对于“应用级”而说的“扩展级”框架是“Yaf（Yet Another Framework）”。

	</p>
	<span class="label label-success">TBC</span>
	</div>
<pre name="code" class="sh_php" linenum="off">
&lt;?php
/**
 * @author ciogao@gmail.com
 */
class AboutController extends Controller
{
	public function init() {
		parent::init();
		$this->setaction('about');
	}
	
	public function indexAction() {
		//加载模板;
	}
}
</pre>
      <hr>
<?php include_once(VIEW_PATH .'/layout/footer.phtml')?>