<div class="c_top">
    <div class="t_tu"><?php echo spall_user::avatar($user_id,90);?>
    </div>
    <div class="t_con">
        <h2><?php echo $userinfo['username'];?></h2>
        <?php if ($this_menu == 'album/listened'){?>
            <span>共订阅<?php echo (int)count($myalbums);?>部图集</span>
        <?php }else{?>
            <span>共<?php echo (int)$userinfo['album_count'];?>部图集</span>
        <?php }?>

        <div class="clear"></div>
            <span class="con_a">
                <a href="<?php echo helper_common::site_url('album/mine');?>"
                   <?php if ($this_menu == 'album/mine') echo 'class="cur3"';?>
                    >我制作的图集</a>
                <a href="<?php echo helper_common::site_url('album/listened');?>"
                   <?php if ($this_menu == 'album/listened'){
                        echo 'class="cur2"';
                    }else{
                        echo 'class="cur1"';
                    }?>
                    >我订阅的图集</a>
            </span>
    </div>
</div>