<div class="c_top">
    <div class="t_tu"><img src="/resources/images/devtmp_avatar_90x90.jpg" width="90" height="90" border="0"/>
    </div>
    <div class="t_con">
        <h2>bcsmc</h2>
        <span>共0部图集</span>

        <div class="clear"></div>
            <span class="con_a">
                <a href="#" class="cur3">我制作的图集</a>
                <a href="#" class="cur1">我订阅的图集</a>
            </span>
    </div>
</div>