<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>不要集</title>
    <link href="style/reset.css" rel="stylesheet" type="text/css">
    <link href="style/index.css" rel="stylesheet" type="text/css">
    <link href="style/responsiveslides.css" rel="stylesheet" type="text/css">
    <!--[if lt IE 9]>
    <script type="text/javascript" src="js/html5.js"></script>
    <![endif]-->
</head>

<body>
<div class="wrap">
    <div class="box">
        <div class="main">
            <div class="index">
                <div class="index-carousel">
                    <ul class="rslides">
                        <li><img src="images/index/01.jpg"></li>
                        <li><img src="images/index/02.jpg"></li>
                        <li><img src="images/index/03.jpg"></li>
                        <li><img src="images/index/04.jpg"></li>
                    </ul>
                </div>
                <h1 class="index-logo">不要集</h1>
                <div class="index_login_box">
                    <div class="login">
                        <div class="text-box float_l email"><input type="email" value="登录邮箱" onFocus="if (value =='登录邮箱'){value =''}" onBlur="if (value ==''){value='登录邮箱'}"></div>
                        <div class="text-box float_l password"><input type="text" value="密码" onFocus="if (value =='密码'){type ='password';value=''}" onBlur="if (value ==''){type='text';value='密码'}"></div>
                        <input type="submit" class="submit" value="登录">
                    </div>
                    <div class="aid">
                        <span class="reg"><a href="#">申请账号</a></span>
                        <span class="autologin"><input type="checkbox"><a href="javascript:;">自动登录</a></span>
                        <span class="findpass"><a href="#">忘记密码了？</a></span>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
            <footer class="footer">
                <div class="links">
                    <a href="#">提问与建议</a>
                    <span>|</span>
                    <a href="#">合作联系</a>
                    <span>|</span>
                    <a href="#">关于我们</a>
                </div>
                <div class="copyright">2013 buyaoji.com  京ICP备 13010651号</div>
            </footer>
        </div>
    </div>
</div>
<script language="javascript" type="text/javascript" src="js/jquery.js"></script>
<script language="javascript" type="text/javascript" src="js/responsiveslides.js"></script>
<script language="javascript" type="text/javascript" src="js/index.js"></script>
</body>
</html>
