    <div class="menu">
        <ul class="nav01">
            <li class="on"><a href="main.html#alllist" class="flip-flop" date-value="alllist.html">随便看看</a></li>
            <li><a href="main.html#hot" class="flip-flop" date-value="hot.html">热门</a></li>
            <li><a href="main.html#new" class="flip-flop" date-value="new.html">最新</a></li>
        </ul>
        <dl class="nav02">
            <dt><span>我的</span></dt>
            <dd>
                <ul>
                    <li><a href="main.html#mylist" class="flip-flop" date-value="mylist.html">我的图集</a></li>
                    <li><a href="main.html#myrass" class="flip-flop" date-value="myrass.html">我的订阅</a></li>
                    <li><a href="main.html#mytags" class="flip-flop" date-value="mytags.html">我的标签</a></li>
                </ul>
            </dd>
        </dl>
        <dl class="nav02">
            <dt><span>品牌推荐</span></dt>
            <dd>
                <ul>
                    <li><a href="javascript:;">品牌推荐1</a></li>
                    <li><a href="javascript:;">品牌推荐1</a></li>
                    <li><a href="javascript:;">品牌推荐1</a></li>
                </ul>
            </dd>
        </dl>
    </div>