<div class="mytags">
    <div class="search">
        <div class="reg_t">
            <span><input type="text" value="搜索感兴趣的标签..." onFocus="if (value =='搜索感兴趣的标签...'){value =''}" onBlur="if (value ==''){value='搜索感兴趣的标签...'}" name="textfield" id="textfield" class="int01" /></span>
            <span><input type="image" src="/resources/images/look.png" width="82" height="32" name="button" id="button" value="" class="z_btn"></span>
        </div>
        <div class="reg_ul">
            <ul>
                <li><a href="#">标签1</a></li>
                <li><a href="#">标签1</a></li>
                <li><a href="#">标标签签1</a></li>
                <li><a href="#">标签1</a></li>
                <li><a href="#">标签标签1</a></li>
                <li><a href="#">标签标签1</a></li>
                <li><a href="#">标签1</a></li>
                <li><a href="#">标标签签1</a></li>
                <li><a href="#">标签1</a></li>
                <li><a href="#">标签标签1</a></li>
                <li><a href="#">标签标签标签1</a></li>
                <li><a href="#">标签1</a></li>
            </ul>
        </div>
    </div>
</div>