<div class="mytags">
    <div class="search-tags">
        <div class="search-bar">
            <input type="text" id="searchContent" class="text" placeholder="搜索感兴趣的标签..."/>
            <input type="image" id="searchBtn" src="/resources/images/look.png">
        </div>
        <div class="tagslist" id="tagsList">
        </div>
    </div>
    <div class="had-gz-tags">
        <dl>
            <dt><span class="num">已关注：10/10</span><strong>已关注的标签</strong></dt>
            <dd id="listenedTags">
            </dd>
        </dl>
    </div>
</div>