<?php include_once(VIEW_PATH .'/layout/header.phtml')?>

<div class="mwidth box">
<div class="album_left">
    <div class="bor_light2">
        <div class="bor_lightt2"></div>
        <div class="album_tit">
            <h1 class="blue"><?php echo $album_info['album_name'];?></h1>
            <a href="javascript:;" class="btn_block btn_modify album_listen" data-album-id="<?php echo $album_info['album_id'];?>">订阅</a>
            <dl>
                <dt>专辑简介</dt>
                <dd><?php echo $album_info['album_remark'];?></dd>
            </dl>
            <a href="javascript:;" class="btn_block">摄影</a>
            <a href="javascript:;" class="btn_block">人物</a>
            <a href="javascript:;" class="btn_block btn_modify">修改</a>
        </div>
        <div class="bor_lightf2"></div>
    </div>
    <div class="box_left">
        <?php include_once(VIEW_PATH.'/index/list.phtml')?>
    </div>
</div>
<div class="box_right">
    <div class="bor_light hourshot">
        <div class="bor_lightt"></div>
        <div class="box_center">
            <div class="hourseot_tit">
                <div class="hourseot_tit_l">
                    <?php echo spall_user::avatar($userinfo_all['user_id'],64);?>
                </div>
                <div class="hourseot_tit_r"><span class="pink"><?php echo $userinfo_all['user_name'];?></span>
                    <a href="javascript:;" class="attention">关注</a>
                </div>
                <div class="hourseot_tit_c"><span><?php echo $userinfo_all['follower_count'];?>支持</span><span><?php echo $userinfo_all['album_count'];?>专辑</span></div>

            </div>
            <h1 class="pink borwu">其它专辑</h1>
            <div class="photo_list">
            <?php echo spall_album::albums($other_album_info);?>
            </div>
        </div>
        <div class="bor_lightf"></div>
    </div>

    <div class="bor_light tu_listright">
        <div class="bor_lightt"></div>
        <div class="box_center">
            <div class="tu_img"><a href="detailed.html"><img src="images/photo02.jpg" /></a> <a href="javascript:;" class="icon_like"><b class="icon icon01">喜欢</b></a> <a href="javascript:;" class="icon_collect"><b class="icon icon02">收藏</b></a> </div>
            <div class="sharenumber"> <b class="icon icon03">2234</b> <b class="icon icon04">2234</b> </div>
        </div>
        <div class="bor_lightf"></div>
    </div>
</div>
</div>

<script>album_listen();</script>

<?php include_once(VIEW_PATH.'/layout/footer.phtml')?>