<?php include_once(VIEW_PATH . '/layout/header.phtml') ?>

<?php include_once(VIEW_PATH . '/common/page_title.phtml') ?>
    <div class="user-set">
        <div class="s_left">
            <div class="sz_01">
                <span>用户名：</span><span><?php echo $userinfo_all['user_name'];?></span>
            </div>
            <div class="sz_01 js-userinfo-item" id="userinfo">
                <p class="item-display">
                    <span>邮箱：<?php echo $userinfo_all['user_email'];?></span>
                    <a href="javascript:;" class="js-edit">[修改]</a>
                </p>
                <div class="item-edit">
                    <form action="">
                        <span>邮箱：</span>
                        <input type="text" name="email" value="<?php echo $userinfo_all['user_email'];?>"/>
                        <a href="javascript:;" class="js-submit">[确定]</a>
                    </form>
                </div>
            </div>
            <div class="sz_01 js-userinfo-item">
                <p class="item-display">
                    <span>性别：<?php echo spall_user::gender($userinfo_all['gender']);?></span>
                    <a href="javascript:;" class="js-edit">[修改]</a>
                </p>
                <div class="item-edit">
                    <form action="">
                        <span>性别：</span>
                        <label for=""><input type="radio" name="gender" value="1"/>宅男</label>
                        <label for=""><input type="radio" name="gender" value="2"/>腐女</label>
                        <a href="javascript:;" class="js-submit">[确定]</a>
                    </form>
                </div>
            </div>
            <div class="sz_01 sz_02">
                <span> 头像：
                    <br/>
                    <a href="javascript:;" class="js-updateAvatarBtn"><img src="<?php echo spall_user::avatarSource($userinfo_all['user_id'],90);?>" alt=""/></a>
                </span>
                <a href="javascript:;" class="js-updateAvatarBtn">[修改]</a>
            </div>
            <div class="sx">
                <div class="sx_left">
                    <ul>
                        <li>
                            <a href="javascript:;" id="updatePasswordBtn">修改密码</a>
                        </li>
<!--                        <li>-->
<!--                            <a href="#">邮箱设置</a>-->
<!--                        </li>-->
                    </ul>
                </div>
                <div class="sx_right" id="updatePassword">
                    <form action="" id="updatePasswordForm">
                        <div class="sx_t01">
                            <span>当前密码：</span>
                        <span>
                            <input type="password" name="pwd[old]" id="oldPwd" class="int001" />
                        </span>
                        </div>
                        <div class="sx_t01">
                            <span>新的密码：</span>
                        <span>
                            <input type="password" name="pwd[new]" id="newPwd" class="int001" />
                        </span>
                        </div>
                        <div class="sx_t01">
                            <span>重复密码：</span>
                        <span>
                            <input type="password" name="pwd[repeat]" id="newPwdRepeat" class="int001" />
                        </span>
                        </div>
                        <div class="sx_t01 sx_t02">
                        <span>
                            <input type="image" src="/resources/images/userinfo_save_pwd.png" width="80" height="23" name="" id="savePwdBtn" value="" />
                        </span>
                        <span class="sx_span">
                            <input type="image" src="/resources/images/userinfo_cancel.png" width="50" height="23" name="" id="cancelBtn" value="" />
                        </span>
                        </div>
                    </form>
                </div>
            </div>
            <div class="clear"></div>
        </div>
    </div>

<script type="text/javascript">
    seajs.use('app/settings/index');
</script>

<?php include_once('updateavatar.phtml') ?>

<?php include_once(VIEW_PATH.'/layout/footer.phtml')?>