<div id="updateAvatarContent" class="update-avatar clearfix">
    <div class="main-content">
        <div id="uploadCtnr" class="upload-avatar">
            <a href="javascript:;" id="uploadAvatar" class="btn_small_important">
                <span class="btn_wrap">
                    上传头像
                </span>
            </a>
        </div>
        <p>
            你可以上传JPG/GIF或PNG文件，大小不要超过5M
        </p>
        <div class="avatar-src upload-item">
            <img src="" class="js-avatar" id="srcAvatar" alt=""/>
            <div class="upload-progress" id="progress"></div>
        </div>
    </div>
    <div class="east-content">
        <p>
            这是你的头像图标，请注意是否清晰。
        </p>
        <div class="avatar-normal">
            <img src="" alt="" class="js-avatar" id="avatarNormalPreview"/>
        </div>
        <div class="avatar-small">
            <img src="" alt="" id="avatarSmallPreview" class="js-avatar"/>
        </div>
    </div>
</div>
