                </div>
                <footer class="footer">
                    <div class="links">
                        <a href="#">提问与建议</a>
                        <span>|</span>
                        <a href="#">合作联系</a>
                        <span>|</span>
                        <a href="#">关于我们</a>
                    </div>
                    <div class="copyright">2013 buyaoji.com  京ICP备 13010651号</div>
                </footer>
            </div>
        </div>
    </div>
</body>
</html>