            </div>
            <footer class="footer">
                <div class="links">
                    <a href="message.html">提问与建议</a>
                    <span>|</span>
                    <a href="contact.html">合作联系</a>
                    <span>|</span>
                    <a href="about.html">关于我们</a>
                </div>
                <div class="copyright">2013 buyaoji.com  京ICP备 13010651号</div>
            </footer>
        </div>
    </div>
</div>
<script type="text/javascript" src="/resources/js/lib/seajs/sea.js" ></script>
<script type="text/javascript" src="/resources/js/lib/seajs/config.js"></script>
</body>
</html>