<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8">
    <title><?php echo $title;?></title>
    <link rel="stylesheet" href="/resources/style/lib/all.css"/>
    <link rel="stylesheet" href="/resources/style/app/all.css"/>
    <script type="text/javascript" src="/resources/js/lib/seajs/sea.js" ></script>
    <script type="text/javascript" src="/resources/js/lib/seajs/config.js"></script>
    <script>
        var $CONFIG = <?php if (isset($config) && is_array($config) && count($config) > 0){
        echo json_encode($config);
        }else{
            echo '{}';
        } ?>
    </script>
    <script type="text/javascript">
        seajs.use('app/layout/header');
    </script>
</head>
<body>
<header class="header">
    <div class="center-ctnr">
        <div class="container">
            <a href="/" class="header-logo"><?php echo $title;?></a>
            <div class="header-user">
                <?php echo spall_user::avatar($user_id,25,'','class="picture"');?>
                <div class="header-tips">
                    <span class="user-name"><?php echo $config['user_name'];?></span>
                    <a class="tip01 js-msgcount" href="/message" id="msgCount"></a>
                    <div class="tip02">
                        <a href="/message" class="ico01">消息<span class="js-msgcount"></span></a>
                        <a href="<?php echo helper_common::site_url('user/set');?>" class="ico02">设置</a>
                        <a href="<?php echo helper_common::site_url('login/out');?>" class="ico03">退出</a>
                    </div>
                </div>
                <a href="/make/album" class="to-make-phos">做图集</a>
            </div>
        </div>
    </div>
</header>
<div class="center-ctnr">
    <div class="container clearfix">