<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8">
    <title><?php echo $title;?></title>
    <link rel="stylesheet" href="/resources/style/lib/all.css"/>
    <link rel="stylesheet" href="/resources/style/app/all.css"/>
</head>
<body>
<div class="wrap">
    <div class="box">
        <div class="main">
            <div class="register register2">
                <div class="top">
                    <div class="top_nei">
                        <div class="alogo"><a href="#" class="logo1"></a></div>
                        <div class="cen">
                            <div class="cen_t">
                                <ul>
                                    <li style="background:none; margin-right:0;"><img src="images/tu01.png" width="25" height="25" /></li>
                                    <li style="background:none;"><a href="#">bcsmc</a><span class="cen_li">10</span></li>
                                    <li><a href="#">做图集</a></li>
                                </ul>
                            </div>
                            <div class="cen_xl">
                                <ul>
                                    <li class="xl_1"><a href="#">消息</a><span>10</span></li>
                                    <li class="xl_2"><a href="#">设置</a></li>
                                    <li class="xl_3"><a href="#">退出</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>
</body>
</html>