<!DOCTYPE html>
<html>
<head>
    <?php include_once(VIEW_PATH . '/layout/header_common.phtml'); ?>
    <script type="text/javascript">
        seajs.use('app/layout/header');
    </script>
</head>
<body>
<header class="header">
    <div class="center-ctnr">
        <div class="container">
            <a href="/" class="header-logo"><?php echo $title;?></a>
            <div class="header-user">
                <?php echo spall_user::avatar($user_id,25,'','class="picture"');?>
                <div class="header-tips">
                    <span class="user-name"><?php echo $config['user_name'];?></span>
                    <a class="tip01 js-msgcount" href="/messages" id="msgCount"></a>
                    <div class="tip02">
                        <a href="<?php echo helper_common::site_url('messages');?>" class="ico01">消息<span class="js-msgcount"></span></a>
                        <a href="<?php echo helper_common::site_url('settings');?>" class="ico02">设置</a>
                        <a href="<?php echo helper_common::site_url('invitation');?>" class="ico01">邀请码</a>
                        <a href="<?php echo helper_common::site_url('login/out');?>" class="ico03">退出</a>
                    </div>
                </div>
                <a href="/make/album" class="to-make-phos">做图集</a>
            </div>
        </div>
    </div>
</header>
<div class="center-ctnr">
    <div class="container clearfix">