<div id="popup_layer" style="display: none;">
    <div class="layer_bg"></div>

    <?php if ($userinfo == false) {?>
    <div id="login" style="display: block;"> <a href="javascript:;" title="关闭" class="close"></a>
        <h1 class="pink">登录</h1>
        <div class="login_left">
            <ul>
                <li>
                    <label class="label">用户名:</label>
                    <input type="text" name="user_name" class="ipt_text">
                </li>
                <li>
                    <label class="label">密　码:</label>
                    <input type="password" name="pwd" class="ipt_text">
                </li>
                <li>
                    <label>
                        <input type="checkbox" class="ipt_checkbox">
                        两周内免登录</label>
                </li>
                <li class="li_tj">
                    <a href="javascript:;" class="btn btn2" id="login_btn_submit"><b>登录</b></a>
                    <a href="javascript:;" class="pink forgetpass">忘记密码</a>
                </li>
            </ul>
        </div>
        <div class="login_right">
            <p>还不是萌友？</p>
            <p><a href="javascript:;" class="btn btn1"><b>现在注册</b></a></p>
            <p><a href="#" class="login_icon1">用微博帐户登录</a></p>
            <p><a href="#" class="login_icon2">用QQ帐号登录</a></p>
            <p><a href="#" class="login_icon3">用淘宝帐户登录</a></p>
        </div>
    </div>
    <?php }?>

    <div id="Incorrect">
        <p class="pink">填写的格式不正确</p>
        <a href="javascript:;" class="btn btn2 close"><b>返回</b></a> </div>
    <div id="success" class="close">发布成功</div>
    <div id="login_prompt"> <a href="javascript:;" title="关闭" class="close"></a>
        <p class="pink">需要登录后才能继续操作<br>
            现在 <a href="#" class="blue">登录</a> 或 <a href="registered.html" class="blue">注册</a></p>
    </div>

    <div id="Favorites"> <a href="javascript:;" title="关闭" class="close"></a>
        <h1 class="pink">收藏</h1>
        <div class="Favorites"> <a href="javascript:;"><img src="images/photo05.jpg" class="pho_left"></a>
            <h2>收藏到</h2>
            <input name="items_id" value="" type="hidden">
            <?php foreach($myalbums as $v){?>
                <input type="radio" name="albums" value="<?php echo $v['album_id'];?>"><?php echo $v['album_name'];?>
            <?php }?><br />
            <a href="javascript:;" class="btn collection"><b>确认收藏</b></a>
            <div class="Favorites_a">
                <input name="" type="text" class="ipt_text">
                <a href="javascript:;" class="btn btn2"><b>创建</b></a>
            </div>
        </div>
    </div>
</div>

<script>
    /*弹出层*/
    $(function(){
        $(".close").click(function(){
            $("#popup_layer").hide(500);
            $("#Login_area,#before_logging").show(300);
        })
    });

    $("#login_btn").click(function(){
        $("#popup_layer").show(300);
    });

    $("#login_btn_submit").click(function(){
       login();
    });

</script>