   <div class="span3 bs-docs-sidebar">
        <ul class="nav nav-list bs-docs-sidenav affix">
          <li class="active"><a href="<?php echo helper_common::site_url('admin')?>"><i class="icon-chevron-right"></i> 管理博客</a></li>
          <li><a href="<?php echo helper_common::site_url('admin/replay')?>"><i class="icon-chevron-right"></i> 管理评论</a></li>
          <li><a href="<?php echo helper_common::site_url('classadmin')?>"><i class="icon-chevron-right"></i>分类管理</a></li>
          <li class=""><a href="<?php echo helper_common::site_url('tagadmin')?>"><i class="icon-chevron-right"></i> tag管理</a></li>
          <li class=""><a href="#buttons"><i class="icon-chevron-right"></i> xx</a></li>
          <li><a href="#images"><i class="icon-chevron-right"></i> xx</a></li>
          <li><a href="#icons"><i class="icon-chevron-right"></i> xx</a></li>
        </ul>
    </div>