<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo $title;?></title>
    <link href="/static/common/style.css" rel="stylesheet" type="text/css" />
    <link href="/static/lib/base.css" rel="stylesheet" type="text/css" />
    <link href="/static/lib/cmp_all.css" rel="stylesheet" type="text/css" />
    <link href="/static/lib/common.css" rel="stylesheet" type="text/css" />
    <link rel="shortcut icon" href="/static/images/favicon.ico" type="image/x-icon"/>
    <script type="text/javascript" src="/static/lib/base.all.js"></script>
    <script type="text/javascript" src="/static/lib/jquery.blockUI.js"></script>
    <script type="text/javascript" src="/static/lib/jquery.fancybox.js"></script>
    <script type="text/javascript" src="/static/lib/jquery.form.js"></script>
    <script type="text/javascript" src="/static/lib/yaf.all.js"></script>
    <script type="text/javascript" src="/static/common/tang.all.js"></script>
    <script src="/static/common/cascade.js" type="text/javascript"></script>
    <script src="/static/common/search.js" type="text/javascript"></script>
</head>
<body>
<div class="header">
    <div class="mwidth"> <a href="javascript:;" class="logo" target="_blank" title="小萌AVI">小萌AVI</a>
        <ul class="nav">
            <li <?php echo $a_index ? $a_index : '';?>><a href="<?php echo helper_common::site_url('index')?>" title="首页" class="nav1">首页</a></li>
            <li <?php echo $a_group ? $a_group : '';?>><a href="<?php echo helper_common::site_url('group')?>" title="分类" class="nav2">分类</a></li>
            <li <?php echo $a_top ? $a_top : '';?>><a href="<?php echo helper_common::site_url('top')?>" title="热门" class="nav3">热门</a></li>
            <li <?php echo $a_periphery ? $a_periphery : '';?>><a href="<?php echo helper_common::site_url('periphery')?>" title="周边" class="nav4">周边</a></li>
        </ul>
        <div class="search">
            <input type="text" class="ipt_text" id="ipt_search" value="输入文字..." />
            <a href="javascript:;" class="search_ok" title="搜索"></a></div>
        <div class="Login_area" id="Login_area"> <a href="javascript:;" id="login_btn" class="btn"><b>登录</b></a> <a href="<?php echo helper_common::site_url('reg')?>" class="btn"><b>注册</b></a><a href="javascript:;" class="btn btn1"><b>发布</b></a> <a href="javascript:;" class="btn btn2"><b>审核</b></a> </div>
        <div class="Login_area" id="Login_area_two"><a href="javascript:;" class="secelt_btn"><img src="images/photo01.gif"/><span>女王奈</span>
                <div class="secelt_up">
                    <p title="个人主页">个人主页</p>
                    <p title="消息">消息</p>
                    <p title="设置">设置</p>
                    <p id="quit" title="退出"><a href="<?php echo helper_common::site_url('user/loginout');?>">退出</a></p>
                </div>
            </a><a href="javascript:;" class="btn btn1"><b>发布</b></a> <a href="javascript:;" class="btn btn2"><b>审核</b></a> </div>
    </div>
</div>
