<?php include_once(VIEW_PATH .'/layout/header.phtml')?>
<div class="mwidth box">
<div class="top_tit">
<a href="javascript:;" class="tit_off">24小时最热</a><a href="javascript:;" class="tit_on">7天最热</a><a href="javascript:;" class="tit_on">TOP250</a>
</div>
  <div class="box_left top_list">
      <?php include_once(VIEW_PATH .'/index/list.phtml')?>
  </div>
</div>

<?php include_once(VIEW_PATH.'/layout/footer.phtml')?>