<?php include_once(VIEW_PATH . '/layout/header.phtml') ?>
    <div class="main">
        <div class="main-wrap">
            <?php include_once(VIEW_PATH . '/common/avatar_tags.phtml') ?>
            <?php include_once(VIEW_PATH . '/common/listentag.phtml') ?>
        </div>
    </div>
    <div class="extra">
        <?php include_once(VIEW_PATH . '/layout/sidebar.phtml') ?>
    </div>

<?php include_once(VIEW_PATH . '/layout/footer.phtml') ?>