<?php include_once(VIEW_PATH . '/layout/header.phtml') ?>
    <div class="container">

        <div class="page-header">
        </div>
        <p>已卖出的订单(单步)</p>

        <div class="tooltip-demo well">
<pre name="code" class="sh_php" linenum="off">
<?php
    print_r($orders_info);
    ?>
</pre>
        </div>

        <p>订单(异步)</p>

        <div class="tooltip-demo well">
<pre name="code" class="sh_php" linenum="off">
<?php
    print_r($orders_info);
    ?>
</pre>
        </div>

        <span class="label label-success">TBD</span>

        <hr>
<?php include_once(VIEW_PATH . '/layout/footer.phtml')?>