<div class="c_top">
    <div class="t_tu">
        <a href="javascript:;"><img src="<?php echo spall_user::avatarSource($user_id,88);?>" class="avatar" width="88" height="88"></a>
    </div>
    <div class="t_con">
        <h2><?php echo $userinfo['user_name'];?></h2>
        <span>共<span class="albumsCount"><?php echo $countAlbums;?></span>部图集</span>

        <div class="clear"></div>
        <a id="follow" class="btn btn-important btn-small" href="javascript:;">关注</a>
        <a id="unfollow" class="btn btn-important btn-small" href="javascript:;">取消关注</a>
    </div>
</div>