<div class="header-info clearfix">
    <div class="header-info-avatar">
        <a href="javascript:;"><img src="<?php echo spall_user::avatarSource($user_id,88);?>" class="avatar" width="88" height="88"></a>
    </div>
    <div class="header-info-content">
        <h2><?php echo $userinfo['user_name'];?></h2>
        <span>共<span class="albumsCount"><?php echo $countAlbums;?></span>部图集</span>

        <div>
            <?php
            if ($ifFollow){
                $class_follow = 'style="display:none;"';
            }else{
                $class_un_follow = 'style="display:none;"';
            }?>
            <a id="follow" data-userid="<?php echo $user_id;?>" class="btn btn-important btn-small" href="javascript:;" <?php echo $class_follow;?>>关注</a>
            <a id="unfollow" data-userid="<?php echo $user_id;?>" class="btn btn-important btn-small" href="javascript:;" <?php echo $class_un_follow;?>>取消关注</a>
        </div>
    </div>
</div>
<script type="text/javascript">
    seajs.use('app/user/avatar');
</script>
