<?php include_once(VIEW_PATH .'/layout/header.phtml')?>

    <div class="page_title">
        <a href="main.html">&lt;&lt;返回首页</a>
    </div>
    <div class="page-title"><img src="/resources/icons/ico02.gif">编辑资料
    </div>
    <div class="user-set">
        <div class="s_left">
            <div class="sz_01">
                <span>用户名：</span><span><?php echo $userinfo_all['user_name'];?></span>
            </div>
            <div class="sz_01 js-userinfo-item">
                <p class="item-display">
                    <span>邮箱：<?php echo $userinfo_all['user_email'];?></span>
                    <a href="javascript:;" class="js-edit">[修改]</a>
                </p>
                <div class="item-edit">
                    <form action="">
                        <span>邮箱：</span>
                        <input type="text" name="email"/>
                        <a href="javascript:;" class="js-submit">[确定]</a>
                    </form>
                </div>
            </div>
            <div class="sz_01 js-userinfo-item">
                <p class="item-display">
                    <span>性别：<?php echo spall_user::gender($userinfo_all['gender']);?></span>
                    <a href="javascript:;" class="js-edit">[修改]</a>
                </p>
                <div class="item-edit">
                    <form action="">
                        <span>性别：</span>
                        <label for=""><input type="radio" name="gender" value="1"/>爷们</label>
                        <label for=""><input type="radio" name="gender" value="2"/>美女</label>
                        <a href="javascript:;" class="js-submit">[确定]</a>
                    </form>
                </div>
            </div>
            <div class="sz_01 sz_02">
                <span> 头像：
                    <br/>
                    <?php echo spall_user::avatar($userinfo_all['user_id'],90);?>
                </span>
                <a href="javascript:;" id="updateAvatarBtn">[修改]</a>
            </div>
            <div class="sx">
                <div class="sx_left">
                    <ul>
                        <li>
                            <a href="javascript:;" id="updatePasswordBtn">修改密码</a>
                        </li>
<!--                        <li>-->
<!--                            <a href="#">邮箱设置</a>-->
<!--                        </li>-->
                    </ul>
                </div>
                <div class="sx_right" id="updatePassword">
                    <form action="" id="updatePasswordForm">
                        <div class="sx_t01">
                            <span>当前密码：</span>
                        <span>
                            <input type="password" name="pwd[old]" id="oldPwd" class="int001" />
                        </span>
                        </div>
                        <div class="sx_t01">
                            <span>新的密码：</span>
                        <span>
                            <input type="password" name="pwd[new]" id="newPwd" class="int001" />
                        </span>
                        </div>
                        <div class="sx_t01">
                            <span>重复密码：</span>
                        <span>
                            <input type="password" name="pwd[repeat]" id="newPwdRepeat" class="int001" />
                        </span>
                        </div>
                        <div class="sx_t01 sx_t02">
                        <span>
                            <input type="image" src="/resources/images/userinfo_save_pwd.png" width="80" height="23" name="" id="savePwdBtn" value="" />
                        </span>
                        <span class="sx_span">
                            <input type="image" src="/resources/images/userinfo_cancel.png" width="50" height="23" name="" id="cancelBtn" value="" />
                        </span>
                        </div>
                    </form>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <!--<div class="qqBox">
            <a href="javascript:;" class="close"></a>
            <div class="cen_k1">
                <div class="cen_z1">
                    <div class="cen_ti1">
                        <span>提问与建议</span>
                    </div>
                    <div class="qq">
                        <a href="#"><img src="images/qq.jpg" width="110" height="39" border="0" /></a>
                        <span>小萌qq交流群：123456789</span>
                    </div>
                    <div class="qq_con">
                        <textarea name="textarea" value="欢迎提出各种问题和建议！" onFocus="if (value =='欢迎提出各种问题和建议！'){value =''}" onBlur="if (value ==''){value='欢迎提出各种问题和建议！'}"id="textarea" class="int041"></textarea>
                    </div>
                    <div class="reg_t021">
                        <span>
                            <input type="text" value="输入邮箱以便我们及时回复" onFocus="if (value =='输入邮箱以便我们及时回复'){value =''}" onBlur="if (value ==''){value='输入邮箱以便我们及时回复'}" name="textfield" id="textfield" class="int031" />
                        </span>
                        <span>
                            <input type="image" src="images/tijiao.jpg" width="80" height="23" name="button" id="button" value="" />
                        </span>
                    </div>
                </div>
            </div>
        </div>-->
    </div>

<script type="text/javascript">
    seajs.use('app/user/set');
</script>

<?php include_once('wincontent_avatar.phtml')?>
<?php include_once('updateavatar.phtml') ?>

<?php include_once(VIEW_PATH.'/layout/footer.phtml')?>