<!Doctype html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8">
    <title><?php echo spall_title::getWebSiteTitle($this_menu);?></title>
    <meta name="keywords" content="<?php echo spall_title::getKeywords();?>"/>
    <link href="/resources/style/app/reset.css" rel="stylesheet" type="text/css">
    <link href="/resources/style/app/login.css" rel="stylesheet" type="text/css">
    <link href="/resources/style/app/login_responsive.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="/resources/style/lib/all.css"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>
<div class="login-main center-ctnr">
   <!-- <div class="index-carousel">
        <ul class="rslides">
            <li><img src="/resources/images/login_0.jpg"></li>
            <li><img src="/resources/images/login_1.jpg"></li>
            <li><img src="/resources/images/login_2.jpg"></li>
            <li><img src="/resources/images/login_3.jpg"></li>
        </ul>
    </div>-->
    <h1 class="index-logo">不要集</h1>
    <div class="index_login_box">
        <div class="login">
            <div class="text-box float_l email">
                <input type="email" id="username" tabindex="1" placeholder="邮箱登录" value=""/></div>
            <div class="text-box float_l password">
                <input type="password" id="pwd" tabindex="2" placeholder="密码"></div>
            <input type="submit" class="submit" id="submit" value="登录">
        </div>
        <div class="aid">
            <span class="reg"><a href="/register">申请账号</a></span>
            <span class="autologin"><label><input id="keepLogin" tabindex="3" name="keep_login" type="checkbox">自动登录</label></span>
            <span class="findpass"><a href="#">忘记密码了？</a></span>
        </div>
    </div>
    <div class="clear"></div>
</div>
<footer class="footer">
    <div class="links">
        <a href="#">提问与建议</a>
        <span>|</span>
        <a href="#">合作联系</a>
        <span>|</span>
        <a href="#">关于我们</a>
    </div>
    <div class="copyright">2013 buyaoji.com  京ICP备 13010651号</div>
</footer>
<script type="text/javascript" src="/resources/js/lib/seajs/sea.js"></script>
<script type="text/javascript" src="/resources/js/lib/seajs/config.js"></script>
<script type="text/javascript">
    seajs.use('app/login/login');
</script>
</body>
</html>
