<?php include_once(VIEW_PATH . '/layout/header.phtml') ?>
    <div class="center-ctnr">
        <div class="container">
            <div class="main">
                <div class="main-wrap">
                    <?php include_once(VIEW_PATH . '/index/avatar.phtml') ?>
                    <?php include_once(VIEW_PATH . '/common/list.phtml') ?>
                </div>
            </div>
            <div class="extra">
                <?php include_once(VIEW_PATH . '/layout/sidebar.phtml') ?>
            </div>
        </div>
    </div>

<?php include_once(VIEW_PATH . '/layout/footer.phtml') ?>