<div class="all-list">
    <ul>

        <?php foreach($myalbums as $album_info){?>
        <li data-albumid="<?php echo $album_info['album_id'];?>">
            <div class="pic">
                <a href="<?php echo helper_common::site_url_album($album_info['album_id']);?>">
                    <img src="<?php echo $album_info['face_url'];?>">
                </a>
            </div>
            <div class="pic-info">
                <dl>
                    <dt><?php echo $album_info['album_name'];?></dt>
                    <dd>
                        <?php echo date('Y/m/d',$album_info['created_time']);?>
                        <span>[<?php echo (int)$album_info['items'];?>图]</span>
                    </dd>
                </dl>
            </div>
            <div class="tip">
                <a href="javascript:;" class="ico01"><?php echo (int)$album_info['hits'];?></a>
                <a href="javascript:;" class="ico02"><?php echo (int)$album_info['likeit'];?></a>
                <a href="javascript:;" class="ico03"><?php echo (int)$album_info['posts'];?></a>
                <input value="编辑" type="button" class="edit">
                <input value="删除" type="button" class="delete">
            </div>
        </li>
        <?php }?>
    </ul>

    <input type="button" class="btn" value="看看别的">
</div>
