<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8">
    <title><?php echo $title;?></title>
    <link rel="stylesheet" href="/resources/style/lib/all.css"/>
    <link rel="stylesheet" href="/resources/style/app/all.css"/>
</head>
<body>
<div class="browsebox">
    <div id="divSlideShowCover" class="slideritem">
        <div class="pic-wap">
            <img src="<?php echo $album_info['face_url'];?>" class="showing">

            <div id="cover">
                <div class="cover-main">
                    <h3 class="pic-title"><?php echo $album_info['album_name'];?></h3>

                    <div class="pics-info">
                        <dl>
                            <dt>
                                <time><?php echo date('Y/m/d',$album_info['created_time']);?></time>
                            <div class="user-name" data-userid="<?php echo helper_common::site_url_user($userinfo['user_id']);?>">
                                by: <?php echo $userinfo['user_name'];?>
                            </div>
                            </dt>
                            <dd>
                                <a href="javascript:;"><img src="/resources/style/app/images/icos/ico07.png" class="ico">
                                    <?php echo (int)$album_info['hits'];?>
                                </a>
                                <a href="javascript:;"><img src="/resources/style/app/images/icos/ico04.png" class="ico">
                                    <?php echo (int)$album_info['likeit'];?>
                                </a>
                                <a href="javascript:;"><img src="/resources/style/app/images/icos/ico05.png" class="ico">
                                    <?php echo (int)$album_info['posts'];?>
                                </a>
                            </dd>
                        </dl>
                        <div class="links">
                            <a href="javascript:;" id="ckepop" class="jiathis jiathis_txt jtico jtico_jiathis"><span>&middot;</span>分享给好友</a>
<!--                            <a href="javascript:;"><span>&middot;</span>预览</a>-->
                        </div>
                        <a href="javascript:;" class="go arrow-next"><img src="/resources/style/app/images/ico_but.png"></a>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <?php foreach($items as $items_info){?>
    <div class="itemshow slideritem">
        <!--此处可选择的class名称为left/center/right  取决于编辑图片时图片的位置-->
        <div class="center">
            <img src="<?php echo $items_info['items_pic'];?>" class="showing"/>
        </div>

        <?php echo $items_info['remark'];?>
        <?php if (strlen($items_info['remark']) > 0) { ?>
            <div class="describe">
                <?php echo $items_info['remark'];?>
            </div>
        <?php } ?>

        <a href="javascript:;" class="arrow_l arrow-prev"></a>
        <a href="javascript:;" class="arrow_r arrow-next"></a>
    </div>
    <?php }?>
    <div class="quark-button">
        <a href="javascript:;" class="collection-button"></a>
        <!--收藏按钮被选中后添加class="on"-->
        <a href="javascript:;" class="comments-button"></a>
        <a href="javascript:;" class="share-button callShare"></a>
    </div>
</div>
<script type="text/javascript" src="/resources/js/lib/seajs/sea.js"></script>
<script type="text/javascript" src="/resources/js/lib/seajs/config.js"></script>
<script type="text/javascript">
    seajs.use('app/album/v');
</script>
<script type="text/javascript" src="http://v2.jiathis.com/code/jia.js" charset="utf-8"></script>
</body>
</html>