<?php include_once(VIEW_PATH . '/layout/header.phtml') ?>

<?php include_once(VIEW_PATH . '/common/page_title.phtml') ?>

    <div class="container">
        <ul>
            <li>
                <h2>一般问题</h2>
                <p class="content">请到&nbsp;<a href="/feedback">提问与建议</a>&nbsp;或发送邮件至xxx@xxx.xxx</p>
            </li>
            <li>
                <h2>QQ群</h2>
                <p class="content">欢迎加入QQ群（64245187），与这里的朋友沟通交流</p>
            </li>
        </ul>

    </div>

<?php include_once(VIEW_PATH . '/layout/footer.phtml') ?>