<div class="header-info clearfix">
    <div class="header-info-avatar">
        <a href="javascript:;"><img src="<?php echo spall_user::avatarSource($user_id,88);?>" class="avatar" width="88" height="88"></a>
    </div>
    <div class="header-info-content">
        <h2><?php echo $userinfo['user_name'];?></h2>

        <span>共关注<span class="albumsCount"><?php echo $follower_from_me_count;?></span>用户</span>

        <div class="header-info-tabs">
            <a href="<?php echo helper_common::site_url('follow');?>"  class="current">我关注的用户</a>
            <span class="sp">|</span>
            <a href="<?php echo helper_common::site_url('tags/mine');?>">我关注的标签</a>
        </div>
    </div>
</div>
