<?php if (is_array($follower_from_me_list) && count($follower_from_me_list) > 0){?>
    <ul class="follows-items clearfix">
        <?php
        foreach($follower_from_me_list as $info){
        ?>

        <li class="follows-item js-follow-item">
            <a href="<?php echo helper_common::site_url_user($info['to_user_id']);?>">
                <img class="follows-item-avatar" src="<?php echo spall_user::avatarSource($info['to_user_id']);?>"/>
            </a>
            <span class="follows-item-username js-name">
                <a href="<?php echo helper_common::site_url_user($info['to_user_id']);?>">
                    <?php echo spall_user::getUserName($info['to_user_id']);?>
                </a>
            </span>
            <a class="follows-item-link js-unfollow" data-userid="<?php echo $info['to_user_id'];?>" href="javascript:;">取消关注</a>
        </li>

        <?php }?>

    </ul>

    <?php echo $sPage;?>
<?php } else { ?>
    <div class="msg-nodata">
        <?php echo spall_nullmsg::getNullMsgs($this_menu);?>
    </div>
<?php } ?>
<script type="text/javascript">
    seajs.use('app/follow/index');
</script>