<?php include_once(VIEW_PATH .'/layout/header.phtml')?>
    <div class="container">
    
    <div class="page-header">
    先取得商品id与更新时间,再通过多个商品信息接口,批量取得商品信息.
	</div>

	<p>正在销售的商品列表</p>
	<div class="tooltip-demo well">
<pre name="code" class="sh_php" linenum="off">
<?php 
print_r($items_info);
?>
</pre>	
	</div>

	<p>单个商品信息</p>
	<div class="tooltip-demo well">
<pre name="code" class="sh_php" linenum="off">
<?php 
print_r($item_info);
?>
</pre>	
	</div>

	<p>多个商品信息</p>
	<div class="tooltip-demo well">
<pre name="code" class="sh_php" linenum="off">
<?php 
print_r($items_list_info);
?>
</pre>	
	</div>

	
	<span class="label label-success">TBD</span>
	
      <hr>
<?php include_once(VIEW_PATH .'/layout/footer.phtml')?>