<!DOCTYPE html>
<html>
<head>
    <?php include_once(VIEW_PATH . '/common/header.phtml'); ?>
</head>
<body>
    <div class="wrap">
        <div class="box">
            <div class="main">
                <div class="register">
                    <a href="/" class="logo">不要集</a>
                    <div class="clear"></div>
                    <div class="reg_begin">
                        <div class="reg_left">
<!--                            <div class="reg_tu">-->
<!--                                <p><img src="/resources/images/avatar_default.jpg" width="75" height="75" /></p>-->
<!--                                <p><a href="#" target="_blank">上传头像</a></p>-->
<!--                            </div>-->
                            <div class="reg_con">
                                <div class="reg_1">
                                    <input type="text" value="" id="username" class="int" placeholder="用户名"/>
                                </div>
                                <div class="reg_1">
                                    <input type="text" value="" id="email" class="int" placeholder="邮箱"/>
                                </div>
                                <div class="reg_1">
                                    <input type="password" value="" id="pwd" class="int" placeholder="密码"/>
                                </div>
                                <div class="reg_1">
                                    <input type="text" value="" id="invitationCode" class="int" placeholder="邀请码"/>
                                </div>
                                <div class="reg_1">
                                    <input type="image" src="/resources/images/reg_btn.png" width="143" height="44"
                                           name="button" id="submit" value="" class="z_btn">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php include_once(VIEW_PATH . '/common/footer.phtml'); ?>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="/resources/js/lib/seajs/sea.js" ></script>
    <script type="text/javascript" src="/resources/js/lib/seajs/config.js"></script>
    <script type="text/javascript">
        seajs.use('app/reg/index');
    </script>
</body>
</html>
