<!DOCTYPE html>
<html>
<head>
    <?php include_once(VIEW_PATH . '/common/header.phtml'); ?>
</head>
<body>
    <div class="wrap">
        <div class="box">
            <div class="main">
                <div class="register">
                    <a href="/" class="logo">不要集</a>
                    <div class="clear"></div>
                    <div class="reg_begin">
                        <div class="reg_left">
<!--                            <div class="reg_tu">-->
<!--                                <p><img src="/resources/images/avatar_default.jpg" width="75" height="75" /></p>-->
<!--                                <p><a href="#" target="_blank">上传头像</a></p>-->
<!--                            </div>-->
                            <form id="regForm">
                                <div class="reg_con">
                                    <div class="reg_1">
                                        <input type="text" value="" name="user_name" id="username" class="int" placeholder="用户名"/>
                                    </div>
                                    <div class="reg_1">
                                        <input type="text" value="" name="email" id="email" class="int" placeholder="邮箱"/>
                                    </div>
                                    <div class="reg_1">
                                        <input type="password" value="" name="pwd" id="pwd" class="int" placeholder="密码"/>
                                    </div>
                                    <div class="reg_1">
                                        <input type="password" value="" name="pwdRepeat" id="pwdRepeat" class="int" placeholder="重复密码"/>
                                    </div>
                                    <div class="reg_1">
                                        <input type="text" value="" name="invitationCode" id="invitationCode" class="int" placeholder="邀请码"/>
                                    </div>
                                    <div class="reg_1 align-center">
                                        <a class="btn btn-middle btn-strong" id="submit" href="javascript:;">注册</a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <?php include_once(VIEW_PATH . '/common/footer.phtml'); ?>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="/resources/js/lib/seajs/sea.js" ></script>
    <script type="text/javascript" src="/resources/js/lib/seajs/config.js"></script>
    <script type="text/javascript">
        seajs.use('app/reg/index');
    </script>
</body>
</html>
