<!DOCTYPE html>
<html>
<head>
    <?php include_once(VIEW_PATH . '/layout/header_common.phtml'); ?>
</head>
<body>
<div class="wrap">
    <div class="box">
        <div class="main">
            <div class="reglater">
                <a href="/" class="logo">不要集</a>

                <?php include_once(VIEW_PATH . '/common/listentag.phtml') ?>
                <a href="/" class="complete-reg">完成注册</a>
            </div>
            <footer class="footer">
                <div class="links">
                    <a href="#">提问与建议</a>
                    <span>|</span>
                    <a href="#">合作联系</a>
                    <span>|</span>
                    <a href="#">关于我们</a>
                </div>
                <div class="copyright">2013 buyaoji.com  京ICP备 13010651号</div>
            </footer>
        </div>
    </div>
</div>
<script type="text/javascript">
    seajs.use('app/reg/listentag');
</script>
</body>
</html>