<!DOCTYPE html>
<html>
<head>
    <?php include_once(VIEW_PATH . '/common/header.phtml'); ?>
</head>
<body>
<div class="center-ctnr main-ctnr">
    <div class="container">
        <div class="reglater">
            <a href="/" class="logo">不要集</a>

            <?php include_once(VIEW_PATH . '/common/listentag.phtml') ?>
            <a href="/" class="complete-reg">完成注册</a>
        </div>
    </div>
</div>
<?php include_once(VIEW_PATH . '/common/footer.phtml'); ?>
</body>
</html>