<div class="header-info clearfix">
    <div class="header-info-avatar">
        <img src="<?php echo spall_user::avatarSource($user_id);?>" height="90">
    </div>
    <div class="header-info-content">
        <h2><?php echo $userinfo['user_name'];?></h2>
        <?php if ($this_menu == 'tags/mine'){?>
            <span>共关注<span class="tag_listened_count">0</span>个标签</span>
        <?php }else{?>
            <span>共<?php echo (int)$userinfo['album_count'];?>部图集</span>
        <?php }?>

    </div>
</div>