<?php if (is_array($myalbums) && count($myalbums) > 0){?>
    <div class="list" id="albumList">
        <ul class="albumlist albumlist-3col">
            <?php foreach($myalbums as $album_info){?>
                <li class="albumitem js-albumitem" data-albumid="<?php echo $album_info['album_id'];?>">
                    <div class="albumitem-wrap">
                        <a href="<?php echo helper_common::site_url_album($album_info['album_id']);?>" target="_blank">
                            <div class="pic">
                                <img src="<?php echo $album_info['face_url'];?>">
                            </div>
                            <div class="pic-info">
                                <dl>
                                    <dt>
                                        <?php echo $album_info['album_name'];?>
                                    </dt>
                                    <dd>
                                        <?php echo date('Y/m/d',$album_info['created_time']);?>
                                        <span>[<?php echo (int)$album_info['items'];?>图]</span>
                                    </dd>
                                </dl>
                            </div>
                        </a>
                        <div class="tip">
                            <a href="javascript:;" class="ico01 js-replay"><?php echo (int)$album_info['posts'];?></a>
                            <a href="javascript:;" class="ico02 <?php if ($album_info['user_id'] != $config['user_id']) echo 'js-collect ';?><?php if (isset($listened_album_ids) && in_array($album_info['album_id'],$listened_album_ids)) echo 'checked';?>"><?php echo (int)$album_info['likeit'];?></a>
                            <a href="<?php echo helper_common::site_url_album($album_info['album_id']);?>" target="_blank" class="ico03 js-detail"><?php echo (int)$album_info['hits'];?></a>
                            <?php if ($user_id == $album_info['user_id'] && $this_menu == 'album/mine'){
                                ?>
                                <a href="<?php echo helper_common::site_url_album_edit($album_info['album_id'])?>" class="edita">编辑</a>
                                <a href="javascript:;" class="edita js-album-remove">删除</a>
                            <?php }else{?>
                                <?php if ($this_menu == 'subscribe'){?>
                                <a href="javascript:;" class="edita js-album-listened-remove">取消订阅</a>
                                <?php }else{?>
                                <div class="user-name">
                                    <a href="<?php echo helper_common::site_url_user($album_info['user_id']);?>">
                                    <?php echo spall_user::username($album_info['user_id']);?>
                                    </a>
                                </div>
                                <?php }?>
                            <?php }?>

                        </div>
                    </div>
                </li>
            <?php }?>
        </ul>
    </div>
    <?php echo $sPage;?>
<?php }else{?>

<div class="msg-nodata">
    <?php echo spall_nullmsg::getNullMsgs($this_menu);?>
</div>

<?php }?>

        <?php if (spall_album::ifJustlook($this_menu)){?>
        <p class="align-center">
            <a href="" class="btn btn-large btn-important get-rand" data-action="<?php echo $this_menu;?>">看看别的</a>
        </p>
        <?php }?>

<script type="text/javascript">
    seajs.use('app/common/list');
</script>