<?php if (is_array($myalbums) && count($myalbums) > 0){?>
    <div class="list">
        <ul>
            <?php foreach($myalbums as $album_info){?>
                <li class="js-albumitem" data-albumid="<?php echo $album_info['album_id'];?>">
                    <div class="pic">
                        <a href="<?php echo helper_common::site_url_album($album_info['album_id']);?>">
                            <img src="<?php echo $album_info['face_url'];?>">
                        </a>
                    </div>
                    <div class="pic-info">
                        <dl>
                            <dt><?php echo $album_info['album_name'];?></dt>
                            <dd>
                                <?php echo date('Y/m/d',$album_info['created_time']);?>
                                <span>[<?php echo (int)$album_info['items'];?>图]</span>
                            </dd>
                        </dl>
                    </div>
                    <div class="tip">
                        <a href="javascript:;" class="ico01"><?php echo (int)$album_info['hits'];?></a>
                        <a href="javascript:;" class="ico02"><?php echo (int)$album_info['likeit'];?></a>
                        <a href="javascript:;" class="ico03"><?php echo (int)$album_info['posts'];?></a>
                        <?php if ($user_id == $album_info['user_id']){
                            ?>
                            <input value="编辑" type="button" class="edit">
                            <input value="删除" type="button" class="delete">
                        <?php }else{?>
                            <div class="user-name"><?php echo spall_user::username($album_info['user_id']);?></div>
                        <?php }?>

                    </div>
                </li>
            <?php }?>
        </ul>

        <?php echo $sPage;?>
<?php }else{?>

<div class="tipgo">你还没有图集，现在去<a href="<?php echo helper_common::site_url('make/album')?>">做一个</a>？</div>

<?php }?>

        <?php if (spall_album::ifJustlook($this_menu)){?>
            <input type="button" class="btn" value="看看别的">
        <?php }?>

<script type="text/javascript">
    seajs.use('app/common/list');
</script>