<div class="choose-tags">
    <div class="search-tags">
        <div class="search-bar">
            <input type="text" id="searchContent" class="text" placeholder="搜索感兴趣的标签..."/>
            <a id="searchBtn" class="btn btn-small btn-important" href="javascript:;">查找</a>
        </div>
        <div class="tagslist" id="tagsList">
        </div>
    </div>
    <div class="had-gz-tags">
        <dl>
            <dt><span class="num">已关注：<span class="tag_listened_count">0</span>/10</span><strong>已关注的标签</strong></dt>
            <dd id="listenedTags">
            </dd>
        </dl>
    </div>
</div>
<script type="text/javascript">
    seajs.use('app/common/listentag');
</script>
