<?php if (is_array($myalbums) && count($myalbums) > 0){?>
    <div class="list" id="albumList">
        <ul class="albumlist albumlist-3col">
            <?php foreach($myalbums as $album_info){?>
                <li class="albumitem js-albumitem" data-albumid="<?php echo $album_info['album_id'];?>">
                    <div class="albumitem-wrap">
                        <a href="<?php echo helper_common::site_url_album($album_info['album_id']);?>" target="_blank">
                            <div class="pic">
                                <img src="<?php echo $album_info['face_url'];?>">
                            </div>
                        </a>
                        <div class="pic-info">
                            <dl>
                                <dt><?php echo $album_info['album_name'];?></dt>
                                <dd>
                                    <?php echo date('Y/m/d',$album_info['created_time']);?>
                                    <span>[<?php echo (int)$album_info['items'];?>图]</span>
                                </dd>
                            </dl>
                        </div>
                        <div class="tip">
                            <a href="javascript:;" class="ico01 js-replay"><?php echo (int)$album_info['posts'];?></a>
                            <a href="javascript:;" class="ico02 <?php if ($album_info['user_id'] != $config['user_id']) echo 'js-collect ';?><?php if (isset($listened_album_ids) && in_array($album_info['album_id'],$listened_album_ids)) echo 'checked';?>"><?php echo (int)$album_info['likeit'];?></a>
                            <a href="<?php echo helper_common::site_url_album($album_info['album_id']);?>" target="_blank" class="ico03 js-detail"><?php echo (int)$album_info['hits'];?></a>
                            <?php if ($user_id == $album_info['user_id']){
                                ?>
                                <a href="<?php echo helper_common::site_url_album_edit($album_info['album_id'])?>" class="edita">编辑</a>
                                <a href="javascript:;" class="edita">删除</a>
                            <?php }else{?>
                                <div class="user-name"><?php echo spall_user::username($album_info['user_id']);?></div>
                            <?php }?>

                        </div>
                    </div>
                </li>
            <?php }?>
        </ul>
    </div>
    <?php echo $sPage;?>
<?php }else{?>

<div class="msg-nodata">
    <?php echo spall_nullmsg::getNullMsgs($this_menu);?>
</div>

<?php }?>

        <?php if (spall_album::ifJustlook($this_menu)){?>
            <input type="button" class="btn_large_normal" value="看看别的">
        <?php }?>

<script type="text/javascript">
    seajs.use('app/common/list');
</script>