<?php
if (is_array($items) && count($items) > 0){
    foreach ($items as $itemsinfo) {
?>
        <div class="bor_light tu_list">
            <div class="bor_lightt"></div>
            <div class="box_center">
                <div class="tu_img"><a href="detailed.html"><img src="<?php echo $itemsinfo['items_pic'];?>" /></a> <a href="javascript:;" class="icon_like"><b class="icon icon01">喜欢</b></a> <a href="javascript:;" class="icon_collect"><b class="icon icon02">收藏</b></a> </div>
                <div class="sharenumber">
                    <b class="icon icon03"><?php echo $itemsinfo['like_hits'];?></b>
                    <b class="icon icon04"><?php echo $itemsinfo['reply_hits'];?></b>
                </div>
                <p class="wen"><?php echo $itemsinfo['remark'];?></p>
                <ul class="ly_list">
                    <li><a href="#"><img class="avatar" src="/static/images/photo01.gif" /></a><a href="#">女王奈:</a>发布了图片到发布了图片到发布了图片到发布了图片到"+.+
                        女王殿"</li>
                    <li><a href="#"><img class="avatar" src="/static/images/photo01.gif" /></a><a href="#">女王奈:</a>发布了图片到发布了图片到发布了图片到发布了图片到"+.+
                        女王殿"</li>
                </ul>
            </div>
            <div class="bor_lightf"></div>
        </div>

<?php
    }

}
?>

<div class="bor_light tu_list">
    <div class="bor_lightt"></div>
    <div class="box_center">
        <div class="tu_img"><a href="#"><img src="/static/images/photo01.jpg" /></a> <a href="javascript:;" class="icon_like"><b class="icon icon01">喜欢</b></a> <a href="javascript:;" class="icon_collect"><b class="icon icon02">收藏</b></a> </div>
        <div class="sharenumber"> <b class="icon icon03">2234</b> <b class="icon icon04">2234</b> </div>
    </div>
    <div class="bor_lightf"></div>
</div>